#!/bin/sh
count=0

echo "${count}"

echo "start while"
while [ ${count} -le 10 ]; do
echo "${count}"
# without interruptions only for testing      
count=$(($count+1))
done
echo "stop while"

echo "${count}"
