#!/bin/sh
#
# WARNING "attention it will go on forever until it is killed"
#
count=0

echo "${count}"

echo "start while"
while [ ${count} -le 10 ]; do
echo "${count}"
        if [ ${count} -eq 7 ]; then
                continue
        fi
count=$(($count+1))
done
echo "stop while"

echo "${count}"
