#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99

PROGRAM="/root/watchdog_mbim"

PID_FILE="/var/run/watchdog_mbim.pid"

start_service() {
    touch $PID_FILE
    procd_open_instance
    procd_set_param command $PROGRAM --pidfile "$PID_FILE"
    procd_set_param pidfile "$PID_FILE"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
    logger 'exec: /root/watchdog_mbim: watchdog started'
}

stop_service() {
    #killall watchdog_mbim
    kill $(cat $PID_FILE)
    rm $PID_FILE
    logger 'exec: /root/watchdog_mbim: watchdog stopped'
}
