#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99

PROGRAM="/root/watchdog_mbim"

# if you want to edit the script this will activate a service other than the main one
# mkdir /tmp/bin; cp /root/watchdog_mbim /tmp/bin; # edit new script; vi /tmp/bin/watchdog_mbim; service watchdog_mbim restart
PROGRAM2="/tmp/bin/watchdog_mbim"

PID_FILE="/var/run/watchdog_mbim.pid"

start_service() {

        # from "https://github.com/openNDS/openNDS/blob/master/linux_openwrt/opennds/files/etc/init.d/opennds"
        #      "https://github.com/openwrt/openwrt/issues/5898"
        # solves "Instance not stopped SIGTERM, sending SIGKILL instead" given 180 seconds wait after doing ifdown wan && ifup wan
        # various sources on: "https://github.com/search?q=repo%3Aopenwrt%2Fpackages+procd_set_param+term_timeout&type=code"
        
        if [ -x $PROGRAM2 ]; then
        procd_open_instance
        procd_set_param term_timeout 240
        procd_set_param command $PROGRAM2
        procd_set_param pidfile "$PID_FILE"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
        
        else
        if [ -x $PROGRAM ]; then
        
        procd_open_instance
        procd_set_param term_timeout 240
        procd_set_param command $PROGRAM
        procd_set_param pidfile "$PID_FILE"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
        
        fi
        fi
}

service_triggers() {
        #
        # from "https://forum.openwrt.org/t/procd-init-interface-trigger-for-non-daemon-executables-that-are-not-running-permanently/58258/8"
        #
        # when it detects an event on the defined interface it does the operation, it helps debugging the service
        # after giving the "ifdown wan" command you should see an event with the command:
        #
        # ubus monitor | grep '"method":"up","data":{"interface":"wan"}}'
        #
        # and as a consequence of this it should restart the service
        #
        procd_open_trigger
        procd_add_interface_trigger "interface.*.up" "wan" /etc/init.d/watchdog_mbim restart
        procd_close_trigger
}
