#!/bin/sh
# Daemon for mbim. Restart LTE connection
#
# Thanks to the work of "yosh781" from "https://github.com/yosh781/Daemon-modem-watchdog_qmi-for-Openwrt"
# Thanks "@antonk" to the support from "https://forum.openwrt.org/t/create-a-sample-procd-init-script/230977"

trap "logger 'exec: /root/watchdog_mbim: watchdog stopped'; exit 0" INT TERM


# waiting to understand if there is a better option at procd level
# for 600 sec from boot not exec nothing
get_uptime_s()
{
        local __uptime
        read -r __uptime _ < /proc/uptime &&
        __uptime="${__uptime%.*}" &&
        case "${__uptime}" in
                ''|*[!0-9]*) false ;;
                *) :
        #esac || { reg_failure "Failed to get uptime from /proc/uptime."; eval "${1}"=0; return 1; }
        esac || { logger "exec: /root/watchdog_mbim: Failed to get uptime from /proc/uptime."; exit 1 }
        eval "${1}"='${__uptime:-0}'
}

get_uptime_s uptime_s
sleep_time=$((600-uptime_s))
case "$sleep_time" in
    -*|'') ;; # do nothing if sleep_time is negative or empty string
    *) sleep "$sleep_time"
esac
# end of the wait


LTEINTERFACE=$(uci -q get network.wan)
if [ ${LTEINTERFACE} != "interface" ]; then
    logger "exec: /root/watchdog_mbim: Interface wan not found in network config"
    exit 0
fi

LTEPROTO=$(uci -q get network.wan.proto)
if [ ${LTEPROTO} != "mbim" ]; then
    logger "exec: /root/watchdog_mbim: WAN interface is not using mbim"
    exit 0
fi

AUTOCONNECT=$(uci -q get network.wan.autoconnect)
if [ ${AUTOCONNECT} != "1" ]; then
    logger "exec: /root/watchdog_mbim: WAN autoconnect is disabled"
    exit 0
fi

while true; do

    # theoretically the "uqmi -m -d /dev/cdc-wdm0 -t 20000 --get-data-status"
    # command should respond in this time:
    #
    # time uqmi -m -d /dev/cdc-wdm0 -t 20000 --get-data-status
    # "connected"
    # real    0m 0.25s
    # user    0m 0.00s
    # sys     0m 0.00s
    #
    # so well below the set timeout
     
    LTESTATUS=$(uqmi -m -d /dev/cdc-wdm0 -t 20000 --get-data-status)
    LTEERROR=$?
    LTEFIND=$(echo ${LTESTATUS} | grep "\"connected\"" | wc -l)

    # uqmi not response into 20 sec
    if [ ${LTEERROR} -ne 0 ]; then
        logger "exec: /root/watchdog_mbim: uqmi not response into 20 sec exec ifdown wan; ifup wan"
        ifdown wan && ifup wan
    fi

    # uqmi does not return "connected"
    if [ ${LTEFIND} -eq "0" ]; then
        logger "exec: /root/watchdog_mbim: lost connection detected exec ifdown wan; ifup wan"
        ifdown wan && ifup wan
    #else
    #    logger "exec: /root/watchdog_mbim: ${LTESTATUS} ${LTEERROR} ${LTEFIND}"
    fi

    sleep 20

done

#exit 0

