#!/bin/sh

program="/tmp/watchdog/ping_test"; # from /root/watchdog_mbim

pingpid="/tmp/watchdog/ping_pid"; # from /root/watchdog_mbim
echo $$ > "$pingpid"

pinglock="/tmp/watchdog/ping_lock"; # lock file

target="8.8.8.8"; # target ping

maxping="300"; # 5 minutes

watchdog_debug_file="/tmp/watchdog/mbim_debug"; # from /root/watchdog_mbim
logheader="exec: $program:"; # logger header message

if [ ! -f "$pinglock" ]; then
touch "$pinglock"
fi

count=0
while [[ "$count" -lt "$maxping" ]]
do
        count=$((count+1))
        ping -c 1 -W 1 "$target" > /dev/null 2>&1
        if [ $? -eq "0" ] && [ -f "$pinglock" ]; then
                wanuptime=$(ubus call network.interface.wan_4 status | grep 'uptime' | grep -o '[0-9]\+')
                logger "$logheader send and received packet form count=$count wanuptime=$wanuptime"
                rm "$pinglock"
                if [ -f "$pingpid" ]; then
                rm "$pingpid"
                exit 0
                fi
        fi
        sleep 1
        if [ "$count" -eq "$maxping" ]; then
                if [ -f "$pinglock" ]; then
                rm "$pinglock"
                fi
                if [ -f "$pingpid" ]; then
                rm "$pingpid"
                fi
        fi
done

if [ -f "$watchdog_debug_file" ]; then
logger "$logheader  stop process count=$count"
fi
